# Generated by Django 3.1.7 on 2021-04-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='text-description'),
            preserve_default=False,
        ),
    ]
